# Generated by Django 5.0.7 on 2024-07-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('table', models.CharField(max_length=255)),
                ('guid', models.UUIDField()),
                ('platform', models.IntegerField()),
                ('_modified', models.IntegerField()),
                ('meta', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Aircraft',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
