from django.db import models

class Aircraft(models.Model):
    user_id = models.IntegerField()
    guid = models.UUIDField()
    platform = models.IntegerField()
    _modified = models.IntegerField()

    # Meta fields
    fin = models.CharField(max_length=50, blank=True)
    sea = models.BooleanField(default=False)
    tmg = models.BooleanField(default(False))
    efis = models.BooleanField(default=False)
    fnpt = models.IntegerField(default=0)
    make = models.CharField(max_length=100)
    run2 = models.BooleanField(default=False)
    aircraft_class = models.IntegerField()  # 'class' is a reserved keyword in Python
    model = models.CharField(max_length=100)
    power = models.IntegerField()
    seats = models.IntegerField()
    active = models.BooleanField(default=True)
    kg5700 = models.BooleanField(default=False)
    rating = models.CharField(max_length=100, blank=True)
    company = models.CharField(max_length=100)
    complex = models.BooleanField(default=False)
    cond_log = models.IntegerField()
    fav_list = models.BooleanField(default(False))
    category = models.IntegerField()
    high_perf = models.BooleanField(default(False))
    sub_model = models.CharField(max_length=100, blank=True)
    aerobatic = models.BooleanField(default(False))
    ref_search = models.CharField(max_length=100)
    reference = models.CharField(max_length=100)
    tailwheel = models.BooleanField(default=False)
    default_app = models.IntegerField()
    default_log = models.IntegerField()
    default_ops = models.IntegerField()
    device_code = models.IntegerField()
    aircraft_code = models.UUIDField()
    default_launch = models.IntegerField()
    record_modified = models.IntegerField()

    def __str__(self):
        return self.reference


class Flight(models.Model):
    user_id = models.IntegerField()
    guid = models.UUIDField()
    platform = models.IntegerField()
    _modified = models.IntegerField()

    # Meta fields
    pf = models.BooleanField(default=False)
    pax = models.IntegerField(default=0)
    fuel = models.IntegerField(default=0)
    deice = models.BooleanField(default=False)
    route = models.CharField(max_length=255, blank=True)
    to_day = models.IntegerField(default=0)
    min_u1 = models.IntegerField(default=0)
    min_u2 = models.IntegerField(default=0)
    min_u3 = models.IntegerField(default=0)
    min_u4 = models.IntegerField(default=0)
    min_xc = models.IntegerField(default=0)
    arr_rwy = models.CharField(max_length=50, blank=True)
    dep_rwy = models.CharField(max_length=50, blank=True)
    ldg_day = models.IntegerField(default=0)
    lift_sw = models.IntegerField(default=0)
    p1_code = models.UUIDField(blank=True, null=True)
    p2_code = models.UUIDField(blank=True, null=True)
    p3_code = models.UUIDField(blank=True, null=True)
    p4_code = models.UUIDField(blank=True, null=True)
    report = models.TextField(blank=True)
    tag_ops = models.CharField(max_length=50, blank=True)
    to_edit = models.BooleanField(default=False)
    min_air = models.IntegerField(default=0)
    min_cop = models.IntegerField(default=0)
    min_ifr = models.IntegerField(default=0)
    min_imt = models.IntegerField(default=0)
    min_pic = models.IntegerField(default=0)
    min_rel = models.IntegerField(default=0)
    min_sfr = models.IntegerField(default=0)
    arr_code = models.UUIDField(blank=True, null=True)
    date_utc = models.DateField()
    dep_code = models.UUIDField(blank=True, null=True)
    hobbs_in = models.IntegerField(default=0)
    holding = models.IntegerField(default=0)
    pairing = models.CharField(max_length=50, blank=True)
    remarks = models.TextField(blank=True)
    sign_box = models.BooleanField(default=False)
    to_night = models.IntegerField(default=0)
    user_num = models.IntegerField(default=0)
    min_dual = models.IntegerField(default=0)
    min_exam = models.IntegerField(default=0)
    crew_list = models.TextField(blank=True)
    date_base = models.DateField()
    fuel_used = models.IntegerField(default=0)
    hobbs_out = models.IntegerField(default=0)
    ldg_night = models.IntegerField(default=0)
    next_page = models.BooleanField(default=False)
    tag_delay = models.CharField(max_length=50, blank=True)
    training = models.CharField(max_length=50, blank=True)
    user_bool = models.BooleanField(default=False)
    user_text = models.CharField(max_length=255, blank=True)
    min_instr = models.IntegerField(default=0)
    min_night = models.IntegerField(default=0)
    min_picus = models.IntegerField(default=0)
    min_total = models.IntegerField(default=0)
    arr_offset = models.IntegerField(default=0)
    date_local = models.DateField()
    dep_offset = models.IntegerField(default=0)
    tag_launch = models.CharField(max_length=50, blank=True)
    tag_lesson = models.CharField(max_length=50, blank=True)
    to_time_utc = models.IntegerField(default=0)
    arr_time_utc = models.IntegerField(default=0)
    base_offset = models.IntegerField(default=0)
    dep_time_utc = models.IntegerField(default=0)
    flight_code = models.UUIDField()
    ldg_time_utc = models.IntegerField(default=0)
    fuel_planned = models.IntegerField(default=0)
    next_summary = models.BooleanField(default=False)
    tag_approach = models.CharField(max_length=50, blank=True)
    aircraft_code = models.UUIDField()
    arr_time_sched = models.IntegerField(default=0)
    dep_time_sched = models.IntegerField(default=0)
    flight_number = models.CharField(max_length=50)
    flight_search = models.CharField(max_length=50)
    record_modified = models.IntegerField()

    def __str__(self):
        return self.flight_number